#!/usr/bin/env python3
import os
import sys
import re

def mime_type(path):
    ext = os.path.splitext(path)[1].lower()
    return {
        ".html": "text/html",
        ".js": "application/javascript",
        ".css": "text/css",
        ".svg": "image/svg+xml",
        ".png": "image/png",
        ".ico": "image/x-icon",
        ".json": "application/json",
        ".woff2": "font/woff2",
        ".woff": "font/woff",
        ".ttf": "font/ttf",
        ".txt": "text/plain",
        ".map": "application/json",
    }.get(ext, "application/octet-stream")

def c_identifier(path):
    name = path.lstrip("/").replace("/", "_").replace(".", "_").replace("-", "_")
    if not name:
        name = "index"
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if name[0].isdigit():
        name = "f" + name
    return name

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_dir> <output_hpp>")
        sys.exit(1)

    input_dir = sys.argv[1]
    output_hpp = sys.argv[2]

    files = []
    for root, dirs, names in os.walk(input_dir):
        for name in names:
            full_path = os.path.join(root, name)
            rel_path = "/" + os.path.relpath(full_path, input_dir)
            files.append((rel_path, full_path))

    files.sort(key=lambda x: x[0])

    lines = []
    lines.append("// Auto-generated by embed_web.py")
    lines.append("#pragma once")
    lines.append("#include <string_view>")
    lines.append("#include <unordered_map>")
    lines.append("#include <cstddef>")
    lines.append("")

    arrays = []
    entries = []

    for rel_path, full_path in files:
        ident = c_identifier(rel_path)
        with open(full_path, "rb") as f:
            data = f.read()

        size = len(data)
        arrays.append((ident, data))

        mime = mime_type(rel_path)
        entries.append((rel_path, ident, size, mime))

    # Generate extern declarations
    for ident, data in arrays:
        lines.append(f"extern const unsigned char {ident}[];")
        lines.append(f"extern const unsigned int {ident}_size;")

    lines.append("")

    # Generate inline lookup function
    lines.append("struct EmbeddedFile {")
    lines.append("    const unsigned char* data;")
    lines.append("    size_t size;")
    lines.append("    std::string_view mime_type;")
    lines.append("};")
    lines.append("")

    lines.append("inline const std::unordered_map<std::string_view, EmbeddedFile>& getEmbeddedFiles() {")
    lines.append("    static const std::unordered_map<std::string_view, EmbeddedFile> files = {")

    for rel_path, ident, size, mime in entries:
        entry = '        {"' + rel_path + '", {' + ident + ', ' + ident + '_size, "' + mime + '"}},'
        lines.append(entry)

    lines.append("    };")
    lines.append("    return files;")
    lines.append("}")
    lines.append("")

    hpp_content = "\n".join(lines) + "\n"

    # Write the arrays to a .cpp file in src/web/
    src_dir = output_hpp.replace("/include/", "/src/").replace("include/", "src/")
    src_dir = os.path.dirname(src_dir)
    os.makedirs(src_dir, exist_ok=True)
    cpp_path = os.path.join(src_dir, "embedded_web_data.cpp")

    cpp_lines = []
    cpp_lines.append("// Auto-generated by embed_web.py — do not edit")
    cpp_lines.append('#include "web/embedded_web.hpp"')
    cpp_lines.append("")

    for ident, data in arrays:
        cpp_lines.append(f"const unsigned char {ident}[] = {{")
        # Split into multiple lines to avoid exceeding compiler line limits (max 65535 chars)
        per_line = 16
        for i in range(0, len(data), per_line):
            chunk = data[i:i + per_line]
            hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
            cpp_lines.append(f"    {hex_bytes},")
        cpp_lines.append("};")
        cpp_lines.append(f"const unsigned int {ident}_size = {len(data)};")
        cpp_lines.append("")

    cpp_content = "\n".join(cpp_lines) + "\n"

    os.makedirs(os.path.dirname(output_hpp), exist_ok=True)

    with open(output_hpp, "w") as f:
        f.write(hpp_content)

    with open(cpp_path, "w") as f:
        f.write(cpp_content)

    total = sum(len(d) for _, d in arrays)
    print(f"Embedded {len(files)} files ({total / 1024:.1f} KB) into {output_hpp} + {cpp_path}")

if __name__ == "__main__":
    main()
